package drs.common;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Represents a real-time alert broadcast by the multi-threaded server to every
 * connected client in the Disaster Response System (DRS).
 *
 * <p>This class supports <strong>Enhanced Feature 2: Real-time Multi-user
 * Alerts &amp; Status Broadcast</strong>. When a high-priority disaster is
 * reported, departments are notified, or resources are dispatched, the server
 * constructs an Alert and pushes it asynchronously to all client sockets so
 * operators see live banner notifications without refreshing.</p>
 *
 * <p>This is a shared transfer object serialized over the network.</p>
 *
 * @author DRS Team
 * @version 2.0 (DRS-Enhanced)
 */
public class Alert implements Serializable {

    /** Serialization version identifier for safe network transfer. */
    private static final long serialVersionUID = 1L;

    // --- Class (static) constants - severity levels ---

    /** Severity constant for critical, high-priority alerts (red banner). */
    public static final String LEVEL_CRITICAL = "CRITICAL";

    /** Severity constant for informational alerts (amber/blue banner). */
    public static final String LEVEL_INFO = "INFO";

    /** Date-time format pattern for alert timestamps. */
    public static final String ALERT_DATE_FORMAT = "HH:mm:ss";

    // --- Instance variables - Rule 16: noun names ---

    /** The severity level of this alert (CRITICAL or INFO). */
    private String level;

    /** A short title summarising the alert. */
    private String title;

    /** The full alert message body. */
    private String message;

    /** The related disaster ID, or 0 if not disaster-specific. */
    private int relatedDisasterId;

    /** The username/source that triggered this alert. */
    private String source;

    /** Timestamp when this alert was generated by the server. */
    private LocalDateTime createdAt;

    // --- Constructor ---

    /**
     * Constructs a new Alert with the timestamp set to the current time.
     *
     * @param level             the severity level (LEVEL_CRITICAL/LEVEL_INFO)
     * @param title             a short alert title
     * @param message           the full alert message
     * @param relatedDisasterId the related disaster ID, or 0 if none
     * @param source            the source/username that triggered the alert
     */
    public Alert(String level,
                 String title,
                 String message,
                 int relatedDisasterId,
                 String source) {
        this.level = level;
        this.title = title;
        this.message = message;
        this.relatedDisasterId = relatedDisasterId;
        this.source = source;
        this.createdAt = LocalDateTime.now();
    } // end constructor

    // --- Accessor (get) methods ---

    /**
     * Returns the severity level of this alert.
     *
     * @return the level string (LEVEL_CRITICAL or LEVEL_INFO)
     */
    public String getLevel() {
        return this.level;
    } // end method getLevel

    /**
     * Returns the short alert title.
     *
     * @return the title string
     */
    public String getTitle() {
        return this.title;
    } // end method getTitle

    /**
     * Returns the full alert message body.
     *
     * @return the message string
     */
    public String getMessage() {
        return this.message;
    } // end method getMessage

    /**
     * Returns the related disaster ID, or 0 if the alert is not tied to a
     * specific disaster.
     *
     * @return the related disaster ID integer
     */
    public int getRelatedDisasterId() {
        return this.relatedDisasterId;
    } // end method getRelatedDisasterId

    /**
     * Returns the source/username that triggered this alert.
     *
     * @return the source string
     */
    public String getSource() {
        return this.source;
    } // end method getSource

    /**
     * Returns the raw alert creation timestamp.
     *
     * @return the LocalDateTime when this alert was created
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    } // end method getCreatedAt

    /**
     * Returns a human-readable formatted string of the alert time.
     *
     * @return formatted time string (HH:mm:ss)
     */
    public String getCreatedAtFormatted() {
        DateTimeFormatter formatter =
                DateTimeFormatter.ofPattern(ALERT_DATE_FORMAT);
        return this.createdAt.format(formatter);
    } // end method getCreatedAtFormatted

    // --- Other methods ---

    /**
     * Returns a formatted string representation of this Alert object.
     *
     * @return formatted alert string
     */
    @Override
    public String toString() {
        return "[" + this.getCreatedAtFormatted() + "] "
                + this.level + " — " + this.title
                + ": " + this.message;
    } // end method toString

} // end class Alert
